version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
      - "5000:5000"
    volumes:
      - .:/app
  mongo:
    image: mongo:8.0.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
